services:
  app:
    build:
      context: ../../../..
      dockerfile: drift/instrumentation/fastapi/e2e-tests/Dockerfile
      args:
        - TUSK_CLI_VERSION=${TUSK_CLI_VERSION:-latest}
    environment:
      - PORT=8000
      - TUSK_ANALYTICS_DISABLED=1
      - PYTHONUNBUFFERED=1
    working_dir: /app

